language: python
sudo: false

python:
  - 2.7

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/master.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/master.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/master.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.5.4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/master.zip
    - pip install https://github.com/cloudify-cosmo/tosca-vcloud-plugin/archive/1.3.1.zip

script:
    - cfy init
    - cfy blueprints validate aws-ec2-blueprint.yaml
    - cfy blueprints validate cloudstack-blueprint.yaml
    - cfy blueprints validate host-pool-blueprint.yaml
    - cfy blueprints validate local-blueprint.yaml
    - cfy blueprints validate openstack-blueprint.yaml
    - cfy blueprints validate openstack-haproxy-blueprint.yaml
    - cfy blueprints validate openstack-nova-net-blueprint.yaml
    - cfy blueprints validate simple-blueprint.yaml
    - cfy blueprints validate softlayer-blueprint.yaml
    - cfy blueprints validate vcloud-blueprint.yaml
    - cfy blueprints validate vsphere-blueprint.yaml
