language: python
sudo: false

python:
  - 2.7

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/3.4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/3.4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/3.4.zip
    - pip install https://github.com/cloudify-cosmo/tosca-vcloud-plugin/archive/1.3.1.zip

script:
    - cfy init
    - cfy blueprints validate -p aws-ec2-blueprint.yaml
    - cfy blueprints validate -p cloudstack-blueprint.yaml
    - cfy blueprints validate -p host-pool-blueprint.yaml
    - cfy blueprints validate -p local-blueprint.yaml
    - cfy blueprints validate -p openstack-blueprint.yaml
    - cfy blueprints validate -p openstack-haproxy-blueprint.yaml
    - cfy blueprints validate -p openstack-nova-net-blueprint.yaml
    - cfy blueprints validate -p simple-blueprint.yaml
    - cfy blueprints validate -p softlayer-blueprint.yaml
    - cfy blueprints validate -p vcloud-blueprint.yaml
    - cfy blueprints validate -p vsphere-blueprint.yaml
    - cfy local init -p local-blueprint.yaml
    - cfy local execute -w install
    - cfy local execute -w uninstall
